import React, { useState } from "react";
import { useSearchParams } from "react-router-dom";
import "./Italian.css";

import Navbar from "../../components/UI/Navbar/Navbar";
import Footer from "../../components/UI/Footer/Footer";
import InputAnswer from "../../components/InputAnswer";
import Flashcard from "../../components/Flashcard/Flashcard";
import InputList from "../../components/InputList";
import AudioPractice from "../../components/AudioPractice/AudioPractice";
import AudioPractice2 from "../../components/AudioPractice2/AudioPractice2";
import Sudoku1 from "../../components/Sudoku/Sudoku1";
import PickHanzi from "../../components/PickHanzi/PickHanzi";
import Dialoog from "../../components/Dialoog/Dialoog";

const First100Words = ({ lessonVocabulary }) => {

  const [searchParams] = useSearchParams();
  const exerciseFromUrl = searchParams.get("exercise");
  const availableExercises = ["Test", "Flashcards", "Sentences", "Phrases", "Sudoku", "Basket"];
  const initialExercise = availableExercises.includes(exerciseFromUrl) ? exerciseFromUrl : "Test";
  const [selectedExercise, setSelectedExercise] = useState(initialExercise);
    const [showPinyin, setShowPinyin] = useState(false);
    const [currentIndex, setCurrentIndex] = useState(0);

    const togglePinyin = () => {
        setShowPinyin((prev) => !prev);
    };  

    const handleExerciseClick = (exerciseName) => {
      setSelectedExercise(exerciseName);
    };

    const handleSearch = (searchInput) => {
      const number = parseInt(searchInput, 10);
  
      if (!isNaN(number) && number >= 1 && number <= sentenceList.length) {
        setCurrentIndex(number - 1);
        console.log(number);
        console.log(currentIndex);
      }
    };

    function shuffleArray(array) {
        for (let i = array.length - 1; i > 0; i--) {
          const j = Math.floor(Math.random() * (i + 1));
          [array[i], array[j]] = [array[j], array[i]];
        }
      }

      const [englishPhraseList, setEnglishPhraseList] = useState([
        "I like you",
        "Don't forget",
        "Don't be silly",
        "I'm back", // I have returned / I have come back
        "I'm here",
        "I'm busy",
        "Don't be ridiculous",
        "Don't wait",
        "Forget it"
      ]);

      const [hanziPhraseList, setHanziPhraseList] = useState([
        "我喜欢你",
        "别忘了",
        "别傻了",
        "我回来了",
        "我在这里",
        "我很忙",
        "别逗了",
        "别等了",
        "别想了"
      ]);

      const [pinyinPhraseList, setPinyinPhraseList] = useState([
        "Wǒ xǐ huān nǐ",
        "Bié wàng le",
        "Bié shǎ le",
        "Wǒ huí lái le",
        "Wǒ zài zhè lǐ",
        "Wǒ hěn máng",
        "Bié dòu le",
        "Bié děng le",
        "Bié xiǎng le"
      ]);

      const [sentenceList, setSentenceList] = useState([
        "I love you",
        "I have many hobbies",
        "Eight people",
        "His dad is a teacher",
        "Let's go",
        "He has a white cat",
        "I am busy in the daytime",
        "One hundred RMB",
        "I am in class 3",
        "I want half a watermelon",
        "I have been in China for half an year",
        "I waited for half a day",
        "I can help you",
        "Thank you for your help",
        "She has many bags",
        "I like to eat baozi",
        "I want a glass of water",
        "I want a cup",
        "Go north",
        "I live in the north",
        "I want to go to Beijing",
        "a book",
        "I want to buy a notebook",
        "He is older than me",
        "Don't worry",
        "Is there anything else?",
        "You can ask others",
        "Are you sick?",
        "There are many patients in the hospital",
        "Is this cup not big?"
      ]);

      const [chineseSentenceList, setChineseSentenceList] = useState([
        "我爱你",
        "我有很多爱好",
        "八个人",
        "他的爸爸是老师",
        "走吧",
        "他有一只白猫",
        "我白天很忙",
        "一百块",
        "我在三班",
        "我要半个西瓜",
        "I have been in China for half an year",
        "I waited for half a day",
        "I can help you",
        "Thank you for your help",
        "She has many bags",
        "I like to eat baozi",
        "I want a glass of water",
        "I want a cup",
        "Go north",
        "I live in the north",
        "I want to go to Beijing",
        "a book",
        "I want to buy a notebook",
        "He is older than me",
        "Don't worry",
        "Is there anything else?",
        "You can ask others",
        "Are you sick?",
        "There are many patients in the hospital",
        "Is this cup not big?"
      ]);

      const [pinyinSentenceList, setPinyinSentenceList] = useState([
        "Wǒ ài nǐ",
        "Wǒ yǒu hěnduō àihào",
        "Bā gè rén",
        "Tā de bàba shì lǎoshī",
        "Zǒu ba",
        "Tā yǒu yī zhǐ bái māo",
        "Wǒ báitiān hěn máng",
        "Yī bǎi kuài",
        "Wǒ zài sān bān",
        "Wǒ yào bàn gè xīguā",
        "I have been in China for half an year",
        "I waited for half a day",
        "I can help you",
        "Thank you for your help",
        "She has many bags",
        "I like to eat baozi",
        "I want a glass of water",
        "I want a cup",
        "Go north",
        "I live in the north",
        "I want to go to Beijing",
        "a book",
        "I want to buy a notebook",
        "He is older than me",
        "Don't worry",
        "Is there anything else?",
        "You can ask others",
        "Are you sick?",
        "There are many patients in the hospital",
        "Is this cup not big?"
      ]);

      const [vocabularyList2, setVocabularyList2] = ([
        { firstLang: "嬉しい", secondLang: "happy", pinyin: "うれしい"},
        { firstLang: "楽しい", secondLang: "fun", pinyin: "たのしい"},
        { firstLang: "安心する", secondLang: "relieved", pinyin: "あんしんする"},
        { firstLang: "気持ちいい", secondLang: "pleasant", pinyin: "きもちいい"},
        { firstLang: "幸せ", secondLang: "happy", pinyin: "しあわせ"},
        { firstLang: "好き", secondLang: "like", pinyin: "すき"},
        { firstLang: "満足する", secondLang: "satisfied", pinyin: "まんぞくする"},
        { firstLang: "ドキドキする", secondLang: "nervous (excited)", pinyin: "どきどきする"},
        { firstLang: "ワクワクする", secondLang: "excited", pinyin: "わくわくする"},
        { firstLang: "感謝する", secondLang: "grateful", pinyin: "かんしゃする"}
      ]);

      const [vocabularyList, setVocabularyList] = useState(lessonVocabulary
        ? lessonVocabulary.map((word) => ({
            firstLang: word.chinese,
            secondLang: word.english,
            pinyin: word.pinyin,
          }))
        : [
        { firstLang: "爱", secondLang: "love", pinyin: "ài" },
        { firstLang: "爱好", secondLang: "hobby", pinyin: "ài hào" },
        { firstLang: "八", secondLang: "eight", pinyin: "bā" },
        { firstLang: "爸爸", secondLang: "dad", pinyin: "bàba" },
        { firstLang: "吧", secondLang: "(interjection particle)", pinyin: "ba" },
        { firstLang: "白（形）", secondLang: "white", pinyin: "bái" },
        { firstLang: "白天", secondLang: "day", pinyin: "bái tiān" },
        { firstLang: "百", secondLang: "hundred", pinyin: "bǎi" },
        { firstLang: "班", secondLang: "class", pinyin: "bān" },
        { firstLang: "半", secondLang: "half", pinyin: "bàn" },
        { firstLang: "半年", secondLang: "half a year", pinyin: "bàn nián" },
        { firstLang: "半天", secondLang: "half day", pinyin: "bàn tiān" },
        { firstLang: "帮", secondLang: "help", pinyin: "bāng" },
        { firstLang: "帮忙", secondLang: "help", pinyin: "bāng máng" },
        { firstLang: "包", secondLang: "package", pinyin: "bāo" },
        { firstLang: "包子", secondLang: "bun", pinyin: "bāo zi" },
        { firstLang: "杯", secondLang: "cup", pinyin: "bēi" },
        { firstLang: "杯子", secondLang: "cup", pinyin: "bēi zi" },
        { firstLang: "北", secondLang: "north", pinyin: "běi" },
        { firstLang: "北边", secondLang: "North side", pinyin: "běi biān" },
        { firstLang: "北京", secondLang: "Beijing", pinyin: "běi jīng" },
        { firstLang: "本（量）", secondLang: "(measure word for books or volumes)", pinyin: "běn" },
        { firstLang: "本子", secondLang: "book", pinyin: "běn zi" },
        { firstLang: "比", secondLang: "particle used for comparison", pinyin: "bǐ" },
        { firstLang: "别（副）", secondLang: "Don’t", pinyin: "bié" },
        { firstLang: "别的", secondLang: "other", pinyin: "bié de" },
        { firstLang: "别人", secondLang: "other people", pinyin: "bié·rén" },
        { firstLang: "病", secondLang: "disease", pinyin: "bìng" },
        { firstLang: "病人", secondLang: "patient", pinyin: "bìng rén" },
        { firstLang: "不大", secondLang: "not big", pinyin: "bú dà" },
        { firstLang: "不对", secondLang: "wrong", pinyin: "bú duì" },
        { firstLang: "不客气", secondLang: "You’re welcome", pinyin: "bú kè qì" },
        { firstLang: "不用", secondLang: "No need to", pinyin: "bú yòng" },
        { firstLang: "不", secondLang: "No", pinyin: "bù" },
        { firstLang: "菜", secondLang: "dish", pinyin: "cài" },
        { firstLang: "茶", secondLang: "tea", pinyin: "chá" },
        { firstLang: "差", secondLang: "differ from; bad; short of", pinyin: "chà" },
        { firstLang: "常", secondLang: "often", pinyin: "cháng" },
        { firstLang: "常常", secondLang: "often", pinyin: "cháng cháng" },
        { firstLang: "唱", secondLang: "sing", pinyin: "chàng" },
        { firstLang: "唱歌", secondLang: "sing", pinyin: "chàng gē" },
        { firstLang: "车", secondLang: "car", pinyin: "chē" },
        { firstLang: "车票", secondLang: "ticket", pinyin: "chē piào" },
        { firstLang: "车上", secondLang: "in the car", pinyin: "chē shàng" },
        { firstLang: "车站", secondLang: "station", pinyin: "chē zhàn" },
        { firstLang: "吃", secondLang: "eat", pinyin: "chī" },
        { firstLang: "吃饭", secondLang: "have meal", pinyin: "chī fàn" },
        { firstLang: "出", secondLang: "out", pinyin: "chū" },
        { firstLang: "出来", secondLang: "come", pinyin: "chū lái" },
        { firstLang: "出去", secondLang: "go out", pinyin: "chū qù" },
        { firstLang: "穿", secondLang: "wear", pinyin: "chuān" },
        { firstLang: "床", secondLang: "bed", pinyin: "chuáng" },
        { firstLang: "次（量）", secondLang: "(measure word for times, frequency)", pinyin: "cì" },
        { firstLang: "从", secondLang: "from", pinyin: "cóng" },
        { firstLang: "错", secondLang: "wrong", pinyin: "cuò" },
        { firstLang: "打（动）", secondLang: "hit, take", pinyin: "dǎ" },
        { firstLang: "打车", secondLang: "take a taxi", pinyin: "dǎ chē" },
        { firstLang: "打电话", secondLang: "make a phone call", pinyin: "dǎ diànhuà" },
        { firstLang: "打开", secondLang: "turn on", pinyin: "dǎ kāi" },
        { firstLang: "打球", secondLang: "play ball", pinyin: "dǎ qiú" },
        { firstLang: "大", secondLang: "large, big", pinyin: "dà" },
        { firstLang: "大学", secondLang: "university", pinyin: "dà xué" },
        { firstLang: "大学生", secondLang: "university student", pinyin: "dà xué shēng" },
        { firstLang: "到", secondLang: "reach", pinyin: "dào" },
        { firstLang: "得到", secondLang: "get", pinyin: "dé dào" },
        { firstLang: "地", secondLang: "ground", pinyin: "dì" },
        { firstLang: "的", secondLang: "of", pinyin: "de" },
        { firstLang: "的时候", secondLang: "when", pinyin: "de shí hòu" },
        { firstLang: "等", secondLang: "wait", pinyin: "děng" },
        { firstLang: "弟弟", secondLang: "younger brother", pinyin: "dì di" },
        { firstLang: "第一", secondLang: "first", pinyin: "dì yī" },
        { firstLang: "点", secondLang: "o'clock", pinyin: "diǎn" },
        { firstLang: "电脑", secondLang: "computer", pinyin: "diàn nǎo" },
        { firstLang: "电视", secondLang: "TV", pinyin: "diàn shì" },
        { firstLang: "电视剧", secondLang: "TV drama", pinyin: "diàn shì jù" },
        { firstLang: "电影", secondLang: "movie", pinyin: "diàn yǐng" },
        { firstLang: "店", secondLang: "shop", pinyin: "diàn" },
        { firstLang: "东", secondLang: "east", pinyin: "dōng" },
        { firstLang: "东边", secondLang: "East side", pinyin: "dōng biān" },
        { firstLang: "东西", secondLang: "thing", pinyin: "dōng xī" },
        { firstLang: "懂", secondLang: "understand", pinyin: "dǒng" },
        { firstLang: "都", secondLang: "all", pinyin: "dōu" },
        { firstLang: "读", secondLang: "read", pinyin: "dú" },
        { firstLang: "读书", secondLang: "study", pinyin: "dú shū" },
        { firstLang: "对", secondLang: "correct", pinyin: "duì" },
        { firstLang: "对不起", secondLang: "I’m sorry", pinyin: "duì bù qǐ" },
        { firstLang: "多", secondLang: "many, much", pinyin: "duō" },
        { firstLang: "多少", secondLang: "how many", pinyin: "duō shǎo" },
        { firstLang: "饿", secondLang: "hungry", pinyin: "è" },
        { firstLang: "二", secondLang: "two", pinyin: "èr" },
        { firstLang: "而且", secondLang: "moreover", pinyin: "ér qiě" },
        { firstLang: "儿子", secondLang: "son", pinyin: "ér zi" },
        { firstLang: "二月", secondLang: "February", pinyin: "èr yuè" },
        { firstLang: "法语", secondLang: "French", pinyin: "fǎ yǔ" },
        { firstLang: "饭馆", secondLang: "restaurant", pinyin: "fàn guǎn" },
        { firstLang: "饭卡", secondLang: "meal card", pinyin: "fàn kǎ" },
        { firstLang: "饭店", secondLang: "hotel", pinyin: "fàn diàn" },
        { firstLang: "饭桌", secondLang: "dining table", pinyin: "fàn zhuō" },
        { firstLang: "方便", secondLang: "convenient", pinyin: "fāng biàn" },
        { firstLang: "房间", secondLang: "room", pinyin: "fáng jiān" },
        { firstLang: "放", secondLang: "put", pinyin: "fàng" },
        { firstLang: "放学", secondLang: "finish school", pinyin: "fàng xué" },
        { firstLang: "非常", secondLang: "very", pinyin: "fēi cháng" },
        { firstLang: "分（钟）", secondLang: "(measure word for minutes)", pinyin: "fēn" },
        { firstLang: "服务员", secondLang: "waiter/waitress", pinyin: "fú wù yuán" },
        { firstLang: "附近", secondLang: "nearby", pinyin: "fù jìn" },
        { firstLang: "父母", secondLang: "parents", pinyin: "fù mǔ" },
        { firstLang: "复习", secondLang: "review", pinyin: "fù xí" },
        { firstLang: "干净", secondLang: "clean", pinyin: "gān jìng" },
        { firstLang: "感冒", secondLang: "catch a cold", pinyin: "gǎn mào" },
        { firstLang: "刚才", secondLang: "just now", pinyin: "gāng cái" },
        { firstLang: "高", secondLang: "high", pinyin: "gāo" },
        { firstLang: "高兴", secondLang: "happy", pinyin: "gāo xìng" },
        { firstLang: "告诉", secondLang: "tell", pinyin: "gào sù" },
        { firstLang: "哥哥", secondLang: "older brother", pinyin: "gē ge" },
        { firstLang: "个", secondLang: "(measure word for general use)", pinyin: "gè" },
        { firstLang: "给", secondLang: "give", pinyin: "gěi" },
        { firstLang: "跟", secondLang: "with", pinyin: "gēn" },
        { firstLang: "工人", secondLang: "Worker", pinyin: "gōngrén" },
        { firstLang: "工作", secondLang: "work", pinyin: "gōngzuò" },
        { firstLang: "关（动）", secondLang: "shut; close; turn off", pinyin: "guān" },
        { firstLang: "关上", secondLang: "close; shut to; turn off", pinyin: "guān shàng" },
        { firstLang: "贵", secondLang: "noble", pinyin: "guì" },
        { firstLang: "国", secondLang: "country; state; nation", pinyin: "guó" },
        { firstLang: "国家", secondLang: "Country", pinyin: "guójiā" },
        { firstLang: "国外", secondLang: "foreign; oversea; abroad", pinyin: "guó wài" },
        { firstLang: "过", secondLang: "pass", pinyin: "guò" },
        { firstLang: "还", secondLang: "also; still; yet", pinyin: "hái" },
        { firstLang: "还是", secondLang: "still", pinyin: "háishi" },
        { firstLang: "还有", secondLang: "also; in addition; besides", pinyin: "hái yǒu" },
        { firstLang: "孩子", secondLang: "Children", pinyin: "háizi" },
        { firstLang: "汉语", secondLang: "Chinese", pinyin: "hànyǔ" },
        { firstLang: "汉字", secondLang: "Chinese character", pinyin: "hàn zì" },
        { firstLang: "好（形）", secondLang: "good", pinyin: "hǎo" },
        { firstLang: "好吃", secondLang: "Yummy", pinyin: "hǎochī" },
        { firstLang: "好看", secondLang: "good looking", pinyin: "hǎo kàn" },
        { firstLang: "好听", secondLang: "pleasant to hear", pinyin: "hǎo tīng" },
        { firstLang: "好玩儿", secondLang: "fun; interesting", pinyin: "hǎo wánr" },
        { firstLang: "号", secondLang: "Number/date", pinyin: "hào" },
        { firstLang: "喝", secondLang: "drink", pinyin: "hē" },
        { firstLang: "和", secondLang: "and", pinyin: "hé" },
        { firstLang: "很", secondLang: "very", pinyin: "hěn" },
        { firstLang: "后", secondLang: "back; behind; after; later", pinyin: "hòu" },
        { firstLang: "后边", secondLang: "behind; back", pinyin: "hòu biān" },
        { firstLang: "后天", secondLang: "day after tomorrow", pinyin: "hòu tiān" },
        { firstLang: "花（名）", secondLang: "flower", pinyin: "huā" },
        { firstLang: "话", secondLang: "word; words", pinyin: "huà" },
        { firstLang: "坏", secondLang: "bad", pinyin: "huài" },
        { firstLang: "还", secondLang: "return; pay back", pinyin: "huán" },
        { firstLang: "回（动）", secondLang: "go back; return", pinyin: "huí" },
        { firstLang: "回答", secondLang: "Answer", pinyin: "huídá" },
        { firstLang: "回到", secondLang: "back to", pinyin: "huí dào" },
        { firstLang: "回家", secondLang: "go home; return home", pinyin: "huí jiā" },
        { firstLang: "回来", secondLang: "come back; return", pinyin: "huí lái" },
        { firstLang: "回去", secondLang: "go back", pinyin: "huí qù" },
        { firstLang: "会（动）", secondLang: "can; be able to", pinyin: "huì" },
        { firstLang: "火车", secondLang: "train", pinyin: "huǒ chē" },
        { firstLang: "机场", secondLang: "Airport", pinyin: "jīchǎng" },
        { firstLang: "机票", secondLang: "air ticket", pinyin: "jī piào" },
        { firstLang: "鸡蛋", secondLang: "Egg", pinyin: "jīdàn" },
        { firstLang: "几", secondLang: "several", pinyin: "jǐ" },
        { firstLang: "记", secondLang: "remember", pinyin: "jì" },
        { firstLang: "记得", secondLang: "remember", pinyin: "jìdé" },
        { firstLang: "记住", secondLang: "remember; keep in mind", pinyin: "jì zhù" },
        { firstLang: "家", secondLang: "home", pinyin: "jiā" },
        { firstLang: "家里", secondLang: "In the home", pinyin: "jiā lǐ" },
        { firstLang: "家人", secondLang: "family", pinyin: "jiā rén" },
        { firstLang: "间", secondLang: "between; measure word for rooms", pinyin: "jiān" },
        { firstLang: "见", secondLang: "see; meet", pinyin: "jiàn" },
        { firstLang: "见面", secondLang: "meet", pinyin: "jiànmiàn" },
        { firstLang: "教", secondLang: "teach", pinyin: "jiāo" },
        { firstLang: "叫（动）", secondLang: "call; be called", pinyin: "jiào" },
        { firstLang: "教学楼", secondLang: "teaching building", pinyin: "jiào xué lóu" },
        { firstLang: "姐姐｜姐", secondLang: "elder sister", pinyin: "jiě jie ｜ jiě" },
        { firstLang: "介绍", secondLang: "introduce", pinyin: "jièshào" },
        { firstLang: "今年", secondLang: "this year", pinyin: "jīn nián" },
        { firstLang: "今天", secondLang: "Today", pinyin: "jīntiān" },
        { firstLang: "进", secondLang: "enter", pinyin: "jìn" },
        { firstLang: "进来", secondLang: "come in", pinyin: "jìn lái" },
        { firstLang: "进去", secondLang: "go in", pinyin: "jìn qù" },
        { firstLang: "九", secondLang: "Nine", pinyin: "jiǔ" },
        { firstLang: "就", secondLang: "as soon as; right away; then", pinyin: "jiù" },
        { firstLang: "觉得", secondLang: "Think", pinyin: "juéde" },
        { firstLang: "开", secondLang: "open", pinyin: "kāi" },
        { firstLang: "开车", secondLang: "drive; drive a car", pinyin: "kāi chē" },
        { firstLang: "开会", secondLang: "have a meeting", pinyin: "kāi huì" },
        { firstLang: "开玩笑", secondLang: "Make fun of", pinyin: "kāiwánxiào" },
        { firstLang: "看", secondLang: "see", pinyin: "kàn" },
        { firstLang: "看病", secondLang: "see a doctor", pinyin: "kàn bìng" },
        { firstLang: "看到", secondLang: "see", pinyin: "kàn dào" },
        { firstLang: "看见", secondLang: "seeing", pinyin: "kànjiàn" },
        { firstLang: "考", secondLang: "test; examine", pinyin: "kǎo" },
        { firstLang: "考试", secondLang: "Examination", pinyin: "kǎoshì" },
        { firstLang: "渴", secondLang: "thirsty", pinyin: "kě" },
        { firstLang: "课", secondLang: "course", pinyin: "kè" },
        { firstLang: "课本", secondLang: "textbook", pinyin: "kè běn" },
        { firstLang: "课文", secondLang: "text", pinyin: "kè wén" },
        { firstLang: "口", secondLang: "mouth", pinyin: "kǒu" },
        { firstLang: "块", secondLang: "block", pinyin: "kuài" },
        { firstLang: "快", secondLang: "fast", pinyin: "kuài" },
        { firstLang: "来", secondLang: "come", pinyin: "lái" },
        { firstLang: "来到", secondLang: "come; arrive", pinyin: "lái dào" },
        { firstLang: "老（形）", secondLang: "old; aged", pinyin: "lǎo" },
        { firstLang: "老人", secondLang: "old people; the aged", pinyin: "lǎo rén" },
        { firstLang: "老师", secondLang: "Teacher", pinyin: "lǎoshī" },
        { firstLang: "了", secondLang: "past tense marker", pinyin: "le" },
        { firstLang: "累", secondLang: "tired", pinyin: "lèi" },
        { firstLang: "冷", secondLang: "cold", pinyin: "lěng" },
        { firstLang: "里", secondLang: "in", pinyin: "lǐ" },
        { firstLang: "里边", secondLang: "inside", pinyin: "lǐ biān" },
        { firstLang: "两（数）", secondLang: "two", pinyin: "liǎng" },
        { firstLang: "零｜〇", secondLang: "zero", pinyin: "líng ｜ líng" },
        { firstLang: "六", secondLang: "Six", pinyin: "liù" },
        { firstLang: "楼", secondLang: "floor", pinyin: "lóu" },
        { firstLang: "楼上", secondLang: "upstairs", pinyin: "lóu shàng" },
        { firstLang: "楼下", secondLang: "downstairs", pinyin: "lóu xià" },
        { firstLang: "路", secondLang: "road", pinyin: "lù" },
        { firstLang: "路口", secondLang: "intersection; crossing", pinyin: "lù kǒu" },
        { firstLang: "路上", secondLang: "on the road", pinyin: "lù shàng" },
        { firstLang: "妈妈｜妈", secondLang: "mom; mother", pinyin: "mā ma ｜ mā" },
        { firstLang: "马路", secondLang: "road; street", pinyin: "mǎ lù" },
        { firstLang: "马上", secondLang: "Right off", pinyin: "mǎshàng" },
        { firstLang: "吗", secondLang: "auxiliary word", pinyin: "ma" },
        { firstLang: "买", secondLang: "buy", pinyin: "mǎi" },
        { firstLang: "慢", secondLang: "slow", pinyin: "màn" },
        { firstLang: "忙", secondLang: "busy", pinyin: "máng" },
        { firstLang: "毛（量）", secondLang: "a fractional unit of money in China (measure word)", pinyin: "máo" },
        { firstLang: "没", secondLang: "no", pinyin: "méi" },
        { firstLang: "没关系", secondLang: "No problem", pinyin: "méiguānxi" },
        { firstLang: "没什么", secondLang: "It’s nothing", pinyin: "méi shén me" },
        { firstLang: "没事儿", secondLang: "It’s okay", pinyin: "méi shìr" },
        { firstLang: "没有", secondLang: "have not; no", pinyin: "méi yǒu" },
        { firstLang: "妹妹｜妹", secondLang: "younger sister", pinyin: "mèi mei ｜ mèi" },
        { firstLang: "门", secondLang: "door", pinyin: "mén" },
        { firstLang: "门口", secondLang: "doorway", pinyin: "mén kǒu" },
        { firstLang: "门票", secondLang: "tickets", pinyin: "mén piào" },
        { firstLang: "们（朋友们）", secondLang: "plural marker for pronouns and a few animate nouns (friends)", pinyin: "men （ péng yǒu men ）" },
        { firstLang: "米饭", secondLang: "Steamed Rice", pinyin: "mǐfàn" },
        { firstLang: "面包", secondLang: "Bread", pinyin: "miànbāo" },
        { firstLang: "面条儿", secondLang: "noodles", pinyin: "miàn tiáor" },
        { firstLang: "名字", secondLang: "Name", pinyin: "míngzi" },
        { firstLang: "明白", secondLang: "clear", pinyin: "míngbai" },
        { firstLang: "明年", secondLang: "next year", pinyin: "míng nián" },
        { firstLang: "明天", secondLang: "Tomorrow", pinyin: "míngtiān" },
        { firstLang: "拿", secondLang: "take", pinyin: "ná" },
        { firstLang: "哪", secondLang: "which", pinyin: "nǎ" },
        { firstLang: "哪里", secondLang: "where", pinyin: "nǎ lǐ" },
        { firstLang: "哪儿", secondLang: "where", pinyin: "nǎr" },
        { firstLang: "哪些", secondLang: "which", pinyin: "nǎ xiē" },
        { firstLang: "那（代）", secondLang: "that", pinyin: "nà" },
        { firstLang: "那边", secondLang: "there", pinyin: "nà biān" },
        { firstLang: "那里", secondLang: "there", pinyin: "nà lǐ" },
        { firstLang: "那儿", secondLang: "there", pinyin: "nàr" },
        { firstLang: "那些", secondLang: "those", pinyin: "nà xiē" },
        { firstLang: "奶", secondLang: "milk", pinyin: "nǎi" },
        { firstLang: "奶奶", secondLang: "grandma", pinyin: "nǎinai" },
        { firstLang: "男", secondLang: "Man", pinyin: "nán" },
        { firstLang: "男孩儿", secondLang: "boy", pinyin: "nán háir" },
        { firstLang: "男朋友", secondLang: "boyfriend", pinyin: "nán péng yǒu" },
        { firstLang: "男人", secondLang: "man", pinyin: "nán ren" },
        { firstLang: "男生", secondLang: "boy", pinyin: "nán shēng" },
        { firstLang: "南", secondLang: "south", pinyin: "nán" },
        { firstLang: "南边", secondLang: "south; south side", pinyin: "nán biān" },
        { firstLang: "难", secondLang: "hard, difficult", pinyin: "nán" },
        { firstLang: "呢", secondLang: "auxiliary word", pinyin: "ne" },
        { firstLang: "能", secondLang: "can", pinyin: "néng" },
        { firstLang: "你", secondLang: "you", pinyin: "nǐ" },
        { firstLang: "你们", secondLang: "you", pinyin: "nǐ men" },
        { firstLang: "年", secondLang: "year", pinyin: "nián" },
        { firstLang: "您", secondLang: "you", pinyin: "nín" },
        { firstLang: "牛奶", secondLang: "milk", pinyin: "niúnǎi" },
        { firstLang: "女", secondLang: "woman", pinyin: "nǚ" },
        { firstLang: "女儿", secondLang: "daughter", pinyin: "nǚ’ér" },
        { firstLang: "女孩儿", secondLang: "girl", pinyin: "nǚ háir" },
        { firstLang: "女朋友", secondLang: "girlfriend", pinyin: "nǚ péng yǒu" },
        { firstLang: "女人", secondLang: "woman", pinyin: "nǚ ren" },
        { firstLang: "女生", secondLang: "girl", pinyin: "nǚ shēng" },
        { firstLang: "旁边", secondLang: "Side", pinyin: "pángbiān" },
        { firstLang: "跑", secondLang: "run", pinyin: "pǎo" },
        { firstLang: "朋友", secondLang: "Friend", pinyin: "péngyou" },
        { firstLang: "票", secondLang: "ticket", pinyin: "piào" },
        { firstLang: "七", secondLang: "Seven", pinyin: "qī" },
        { firstLang: "起", secondLang: "get up; start; rise", pinyin: "qǐ" },
        { firstLang: "起床", secondLang: "Get up", pinyin: "qǐchuáng" },
        { firstLang: "起来", secondLang: "get up", pinyin: "qǐlái" },
        { firstLang: "汽车", secondLang: "car", pinyin: "qì chē" },
        { firstLang: "前", secondLang: "front", pinyin: "qián" },
        { firstLang: "前边", secondLang: "in front", pinyin: "qián biān" },
        { firstLang: "前天", secondLang: "the day before yesterday", pinyin: "qián tiān" },
        { firstLang: "钱", secondLang: "money", pinyin: "qián" },
        { firstLang: "钱包", secondLang: "wallet", pinyin: "qián bāo" },
        { firstLang: "请", secondLang: "please", pinyin: "qǐng" },
        { firstLang: "请假", secondLang: "ask for leave", pinyin: "qǐngjià" },
        { firstLang: "请进", secondLang: "please come in", pinyin: "qǐng jìn" },
        { firstLang: "请问", secondLang: "excuse me", pinyin: "qǐng wèn" },
        { firstLang: "请坐", secondLang: "please have a seat", pinyin: "qǐng zuò" },
        { firstLang: "球", secondLang: "ball", pinyin: "qiú" },
        { firstLang: "去", secondLang: "go", pinyin: "qù" },
        { firstLang: "去年", secondLang: "Last year", pinyin: "qùnián" },
        { firstLang: "热", secondLang: "heat", pinyin: "rè" },
        { firstLang: "人", secondLang: "people", pinyin: "rén" },
        { firstLang: "认识", secondLang: "know", pinyin: "rènshi" },
        { firstLang: "认真", secondLang: "earnest", pinyin: "rènzhēn" },
        { firstLang: "日", secondLang: "date", pinyin: "rì" },
        { firstLang: "日期", secondLang: "Date", pinyin: "rìqī" },
        { firstLang: "肉", secondLang: "meat", pinyin: "ròu" },
        { firstLang: "三", secondLang: "Three", pinyin: "sān" },
        { firstLang: "山", secondLang: "mountain", pinyin: "shān" },
        { firstLang: "商场", secondLang: "mall; shopping mall", pinyin: "shāng chǎng" },
        { firstLang: "商店", secondLang: "Shop", pinyin: "shāngdiàn" },
        { firstLang: "上", secondLang: "upper", pinyin: "shàng" },
        { firstLang: "上班", secondLang: "go to work", pinyin: "shàngbān" },
        { firstLang: "上边", secondLang: "above; on", pinyin: "shàng biān" },
        { firstLang: "上车", secondLang: "get on", pinyin: "shàng chē" },
        { firstLang: "上次", secondLang: "last time", pinyin: "shàng cì" },
        { firstLang: "上课", secondLang: "attend class; have a class", pinyin: "shàng kè" },
        { firstLang: "上网", secondLang: "Surf the Internet", pinyin: "shàngwǎng" },
        { firstLang: "上午", secondLang: "morning", pinyin: "shàngwǔ" },
        { firstLang: "上学", secondLang: "go to school", pinyin: "shàng xué" },
        { firstLang: "少", secondLang: "less", pinyin: "shǎo" },
        { firstLang: "谁", secondLang: "who", pinyin: "shéi" },
        { firstLang: "身上", secondLang: "body; on one’s body", pinyin: "shēn shàng" },
        { firstLang: "身体", secondLang: "body", pinyin: "shēntǐ" },
        { firstLang: "什么", secondLang: "What", pinyin: "shénme" },
        { firstLang: "生病", secondLang: "Fall ill", pinyin: "shēngbìng" },
        { firstLang: "生气", secondLang: "get angry", pinyin: "shēngqì" },
        { firstLang: "生日", secondLang: "Birthday", pinyin: "shēngrì" },
        { firstLang: "十", secondLang: "Ten", pinyin: "shí" },
        { firstLang: "时候", secondLang: "time", pinyin: "shíhou" },
        { firstLang: "时间", secondLang: "time", pinyin: "shíjiān" },
        { firstLang: "事", secondLang: "thing", pinyin: "shì" },
        { firstLang: "试", secondLang: "try", pinyin: "shì" },
        { firstLang: "是", secondLang: "yes", pinyin: "shì" },
        { firstLang: "是不是", secondLang: "isn’t it?", pinyin: "shì bú shì" },
        { firstLang: "手", secondLang: "hand", pinyin: "shǒu" },
        { firstLang: "手机", secondLang: "Mobile phone", pinyin: "shǒujī" },
        { firstLang: "书", secondLang: "book", pinyin: "shū" },
        { firstLang: "书包", secondLang: "school bag", pinyin: "shū bāo" },
        { firstLang: "书店", secondLang: "bookstore", pinyin: "shū diàn" },
        { firstLang: "树", secondLang: "tree", pinyin: "shù" },
        { firstLang: "水", secondLang: "water", pinyin: "shuǐ" },
        { firstLang: "水果", secondLang: "Fruits", pinyin: "shuǐguǒ" },
        { firstLang: "睡", secondLang: "sleep", pinyin: "shuì" },
        { firstLang: "睡觉", secondLang: "sleep", pinyin: "shuìjiào" },
        { firstLang: "说", secondLang: "speak", pinyin: "shuō" },
        { firstLang: "说话", secondLang: "talk", pinyin: "shuōhuà" },
        { firstLang: "四", secondLang: "Four", pinyin: "sì" },
        { firstLang: "送", secondLang: "give", pinyin: "sòng" },
        { firstLang: "岁", secondLang: "year, age", pinyin: "suì" },
        { firstLang: "他", secondLang: "he", pinyin: "tā" },
        { firstLang: "他们", secondLang: "they", pinyin: "tā men" },
        { firstLang: "她", secondLang: "she", pinyin: "tā" },
        { firstLang: "她们", secondLang: "they", pinyin: "tā men" },
        { firstLang: "太", secondLang: "too", pinyin: "tài" },
        { firstLang: "天", secondLang: "day", pinyin: "tiān" },
        { firstLang: "天气", secondLang: "weather", pinyin: "tiānqì" },
        { firstLang: "听", secondLang: "hear", pinyin: "tīng" },
        { firstLang: "听到", secondLang: "hear", pinyin: "tīng dào" },
        { firstLang: "听见", secondLang: "hear", pinyin: "tīng jiàn" },
        { firstLang: "听写", secondLang: "dictation; dictate", pinyin: "tīng xiě" },
        { firstLang: "同学", secondLang: "Classmate", pinyin: "tóngxué" },
        { firstLang: "图书馆", secondLang: "Library", pinyin: "túshūguǎn" },
        { firstLang: "外", secondLang: "abroad, outside", pinyin: "wài" },
        { firstLang: "外边", secondLang: "outside", pinyin: "wài biān" },
        { firstLang: "外国", secondLang: "foreign country", pinyin: "wài guó" },
        { firstLang: "外语", secondLang: "foreign language", pinyin: "wài yǔ" },
        { firstLang: "玩儿", secondLang: "play", pinyin: "wánr" },
        { firstLang: "晚", secondLang: "late", pinyin: "wǎn" },
        { firstLang: "晚饭", secondLang: "dinner", pinyin: "wǎn fàn" },
        { firstLang: "晚上", secondLang: "Night", pinyin: "wǎnshang" },
        { firstLang: "网上", secondLang: "online", pinyin: "wǎng shàng" },
        { firstLang: "网友", secondLang: "net friend", pinyin: "wǎng yǒu" },
        { firstLang: "忘", secondLang: "forget", pinyin: "wàng" },
        { firstLang: "忘记", secondLang: "forget", pinyin: "wàngjì" },
        { firstLang: "问", secondLang: "ask", pinyin: "wèn" },
        { firstLang: "我", secondLang: "I", pinyin: "wǒ" },
        { firstLang: "我们", secondLang: "We", pinyin: "wǒmen" },
        { firstLang: "五", secondLang: "Five", pinyin: "wǔ" },
        { firstLang: "午饭", secondLang: "lunch", pinyin: "wǔ fàn" },
        { firstLang: "西", secondLang: "west", pinyin: "xī" },
        { firstLang: "西边", secondLang: "west; west side", pinyin: "xī biān" },
        { firstLang: "洗", secondLang: "wash", pinyin: "xǐ" },
        { firstLang: "洗手间", secondLang: "Restroom", pinyin: "xǐshǒujiān" },
        { firstLang: "喜欢", secondLang: "like", pinyin: "xǐhuan" },
        { firstLang: "下（名、动）", secondLang: "below; under; next; go down; get off", pinyin: "xià" },
        { firstLang: "下班", secondLang: "get off work", pinyin: "xià bān" },
        { firstLang: "下边", secondLang: "below; under", pinyin: "xià biān" },
        { firstLang: "下车", secondLang: "get off", pinyin: "xià chē" },
        { firstLang: "下次", secondLang: "next time", pinyin: "xià cì" },
        { firstLang: "下课", secondLang: "finish class", pinyin: "xià kè" },
        { firstLang: "下午", secondLang: "Afternoon", pinyin: "xiàwǔ" },
        { firstLang: "下雨", secondLang: "rain", pinyin: "xiàyǔ" },
        { firstLang: "先", secondLang: "before", pinyin: "xiān" },
        { firstLang: "先生", secondLang: "Sir", pinyin: "xiānsheng" },
        { firstLang: "现在", secondLang: "Now", pinyin: "xiànzài" },
        { firstLang: "想", secondLang: "think", pinyin: "xiǎng" },
        { firstLang: "小", secondLang: "Small", pinyin: "xiǎo" },
        { firstLang: "小孩儿", secondLang: "child; kid", pinyin: "xiǎo háir" },
        { firstLang: "小姐", secondLang: "Miss", pinyin: "xiǎojiě" },
        { firstLang: "小朋友", secondLang: "child; kid", pinyin: "xiǎo péng yǒu" },
        { firstLang: "小时", secondLang: "hour", pinyin: "xiǎoshí" },
        { firstLang: "小学", secondLang: "primary school; elementary school", pinyin: "xiǎo xué" },
        { firstLang: "小学生", secondLang: "elementary school student", pinyin: "xiǎo xué shēng" },
        { firstLang: "笑", secondLang: "laugh", pinyin: "xiào" },
        { firstLang: "写", secondLang: "write", pinyin: "xiě" },
        { firstLang: "谢谢", secondLang: "Thank you", pinyin: "xièxie" },
        { firstLang: "新", secondLang: "new", pinyin: "xīn" },
        { firstLang: "新年", secondLang: "New Year", pinyin: "xīn nián" },
        { firstLang: "星期", secondLang: "week", pinyin: "xīngqī" },
        { firstLang: "星期日", secondLang: "Sunday", pinyin: "xīng qī rì" },
        { firstLang: "星期天", secondLang: "Sunday", pinyin: "xīng qī tiān" },
        { firstLang: "行", secondLang: "That’s ok", pinyin: "xíng" },
        { firstLang: "休息", secondLang: "Rest", pinyin: "xiūxi" },
        { firstLang: "学", secondLang: "learn; study", pinyin: "xué" },
        { firstLang: "学生", secondLang: "Student", pinyin: "xuésheng" },
        { firstLang: "学习", secondLang: "Study", pinyin: "xuéxí" },
        { firstLang: "学校", secondLang: "School", pinyin: "xuéxiào" },
        { firstLang: "学院", secondLang: "college; academy", pinyin: "xué yuàn" },
        { firstLang: "要（动）", secondLang: "want", pinyin: "yào" },
        { firstLang: "爷爷", secondLang: "grandpa", pinyin: "yéye" },
        { firstLang: "也", secondLang: "also", pinyin: "yě" },
        { firstLang: "页", secondLang: "page", pinyin: "yè" },
        { firstLang: "一", secondLang: "One", pinyin: "yī" },
        { firstLang: "衣服", secondLang: "clothes", pinyin: "yīfu" },
        { firstLang: "医生", secondLang: "Doctor", pinyin: "yīshēng" },
        { firstLang: "医院", secondLang: "Hospital", pinyin: "yīyuàn" },
        { firstLang: "一半", secondLang: "half", pinyin: "yí bàn" },
        { firstLang: "一会儿", secondLang: "A little while", pinyin: "yíhuìr" },
        { firstLang: "一块儿", secondLang: "together", pinyin: "yí kuàir" },
        { firstLang: "一下儿", secondLang: "a little bit", pinyin: "yí xiàr" },
        { firstLang: "一样", secondLang: "equally", pinyin: "yíyàng" },
        { firstLang: "一边", secondLang: "One side", pinyin: "yìbiān" },
        { firstLang: "一点儿", secondLang: "a little bit", pinyin: "yīdiǎnr" },
        { firstLang: "一起", secondLang: "together", pinyin: "yìqǐ" },
        { firstLang: "一些", secondLang: "some", pinyin: "yì xiē" },
        { firstLang: "用", secondLang: "use", pinyin: "yòng" },
        { firstLang: "有", secondLang: "have", pinyin: "yǒu" },
        { firstLang: "有的", secondLang: "some", pinyin: "yǒu de" },
        { firstLang: "有名", secondLang: "Famous", pinyin: "yǒumíng" },
        { firstLang: "有时候｜有时", secondLang: "sometimes", pinyin: "yǒu shí hòu ｜ yǒu shí" },
        { firstLang: "有（一）些", secondLang: "some", pinyin: "yǒu （ yì ） xiē" },
        { firstLang: "有用", secondLang: "useful", pinyin: "yǒu yòng" },
        { firstLang: "右", secondLang: "right", pinyin: "yòu" },
        { firstLang: "右边", secondLang: "Right", pinyin: "yòubian" },
        { firstLang: "雨", secondLang: "rain", pinyin: "yǔ" },
        { firstLang: "元", secondLang: "element; Yuan", pinyin: "yuán" },
        { firstLang: "远", secondLang: "far", pinyin: "yuǎn" },
        { firstLang: "月", secondLang: "month", pinyin: "yuè" },
        { firstLang: "再", secondLang: "again", pinyin: "zài" },
        { firstLang: "再见", secondLang: "Bye", pinyin: "zàijiàn" },
        { firstLang: "在", secondLang: "stay; in process of", pinyin: "zài" },
        { firstLang: "在家", secondLang: "at home", pinyin: "zài jiā" },
        { firstLang: "早", secondLang: "early", pinyin: "zǎo" },
        { firstLang: "早饭", secondLang: "breakfast", pinyin: "zǎo fàn" },
        { firstLang: "早上", secondLang: "Morning", pinyin: "zǎoshang" },
        { firstLang: "怎么", secondLang: "How", pinyin: "zěnme" },
        { firstLang: "站（名）", secondLang: "station", pinyin: "zhàn" },
        { firstLang: "找", secondLang: "look for", pinyin: "zhǎo" },
        { firstLang: "找到", secondLang: "find", pinyin: "zhǎo dào" },
        { firstLang: "这", secondLang: "Here (here)", pinyin: "zhè" },
        { firstLang: "这边", secondLang: "here", pinyin: "zhè biān" },
        { firstLang: "这里", secondLang: "here", pinyin: "zhè lǐ" },
        { firstLang: "这儿", secondLang: "here", pinyin: "zhèr" },
        { firstLang: "这些", secondLang: "these", pinyin: "zhè xiē" },
        { firstLang: "着", secondLang: "in process of", pinyin: "zhe" },
        { firstLang: "真", secondLang: "really", pinyin: "zhēn" },
        { firstLang: "真的", secondLang: "really", pinyin: "zhēn de" },
        { firstLang: "正（副）", secondLang: "just; exactly", pinyin: "zhèng" },
        { firstLang: "正在", secondLang: "in process of", pinyin: "zhèngzài" },
        { firstLang: "知道", secondLang: "know", pinyin: "zhīdào" },
        { firstLang: "知识", secondLang: "knowledge", pinyin: "zhīshi" },
        { firstLang: "中", secondLang: "middle; in", pinyin: "zhōng" },
        { firstLang: "中国", secondLang: "China", pinyin: "zhōngguó" },
        { firstLang: "中间", secondLang: "Middle", pinyin: "zhōngjiān" },
        { firstLang: "中文", secondLang: "Chinese", pinyin: "zhōngwén" },
        { firstLang: "中午", secondLang: "Noon", pinyin: "zhōngwǔ" },
        { firstLang: "中学", secondLang: "middle school", pinyin: "zhōng xué" },
        { firstLang: "中学生", secondLang: "middle School student", pinyin: "zhōng xué shēng" },
        { firstLang: "重", secondLang: "heavy", pinyin: "zhòng" },
        { firstLang: "重要", secondLang: "important", pinyin: "zhòngyào" },
        { firstLang: "住", secondLang: "live", pinyin: "zhù" },
        { firstLang: "准备", secondLang: "Get ready", pinyin: "zhǔnbèi" },
        { firstLang: "桌子", secondLang: "Table", pinyin: "zhuōzi" },
        { firstLang: "字", secondLang: "word, character", pinyin: "zì" },
        { firstLang: "子（桌子）", secondLang: "noun suffix (table)", pinyin: "zi （ zhuō zi ）" },
        { firstLang: "走", secondLang: "go, walk", pinyin: "zǒu" },
        { firstLang: "走路", secondLang: "walk", pinyin: "zǒu lù" },
        { firstLang: "最", secondLang: "most", pinyin: "zuì" },
        { firstLang: "最好", secondLang: "Best", pinyin: "zuìhǎo" },
        { firstLang: "最后", secondLang: "Last", pinyin: "zuìhòu" },
        { firstLang: "昨天", secondLang: "Yesterday", pinyin: "zuótiān" },
        { firstLang: "左", secondLang: "left", pinyin: "zuǒ" },
        { firstLang: "左边", secondLang: "left", pinyin: "zuǒbian" },
        { firstLang: "坐", secondLang: "sit", pinyin: "zuò" },
        { firstLang: "坐下", secondLang: "sit down", pinyin: "zuò xià" },
        { firstLang: "做", secondLang: "do", pinyin: "zuò" },
      ]);
  
        const pinyin = vocabularyList.map(word => word.pinyin)
        const answers = vocabularyList.map(word => word.secondLang);
        const words = vocabularyList.map(word => word.secondLang);
        const labelValues = vocabularyList.map(word => word.firstLang);
        shuffleArray(words);

    return (
        <div className="parent_container_app">
          <Navbar onGameSelect={handleExerciseClick} onSearch={handleSearch}/>
          {selectedExercise === "Test" &&  <InputList correctAnswers={answers} words={words} labelValues={labelValues} pinyin={pinyin} showPinyin={showPinyin} togglePinyin={togglePinyin}/>}
          {selectedExercise === "Flashcards" && <div className="flashcard_container">
                    {vocabularyList.map((word, index) => (
                      <Flashcard
                        key={index}
                        german={word.firstLang}
                        french={word.secondLang}
                        pinyin={word.pinyin}
                        showPinyin={showPinyin}
                      />
                    ))}
                  </div>}
          {selectedExercise === "Sentences" && <AudioPractice shuffleArray={shuffleArray} englishSentenceList={sentenceList} hanziSentenceList={chineseSentenceList} pinyinSentenceList={pinyinSentenceList} onSearch={handleSearch} selectedIndex={currentIndex}/>}
          {selectedExercise === "Phrases" && <AudioPractice2 shuffleArray={shuffleArray} englishSentenceList={englishPhraseList} hanziSentenceList={hanziPhraseList} pinyinSentenceList={pinyinPhraseList} onSearch={handleSearch} selectedIndex={currentIndex}/>}
          {selectedExercise === "Sudoku" && <Sudoku1/>}
          {selectedExercise === "Basket" && <PickHanzi/>}
          {/* {selectedExercise === "Dialoog" && <Dialoog />} */}
          <Footer showPinyin={showPinyin} togglePinyin={togglePinyin}/>
        </div>
    )
}

export default First100Words;