export const lesson1Vocabulary = [
  { english: "едно", chinese: "一", pinyin: "yī" },
  { english: "две", chinese: "二", pinyin: "èr" },
  { english: "три", chinese: "三", pinyin: "sān" },
  { english: "човек", chinese: "人", pinyin: "rén" },
  { english: "голям", chinese: "大", pinyin: "dà" },
  { english: "малък", chinese: "小", pinyin: "xiǎo" },
  { english: "уста", chinese: "口", pinyin: "kǒu" },
  { english: "слънце, ден", chinese: "日", pinyin: "rì" },
  { english: "око", chinese: "目", pinyin: "mù" },
  { english: "бяло", chinese: "白", pinyin: "bái" },
  { english: "майка", chinese: "妈妈", pinyin: "māma" },
  { english: "добре", chinese: "好", pinyin: "hǎo" },
  { english: "жена", chinese: "女", pinyin: "nǚ" },
  { english: "кон", chinese: "马", pinyin: "mǎ" },
  { english: "небе, ден", chinese: "天", pinyin: "tiān" },
  { english: "дете", chinese: "子", pinyin: "zǐ" },
  { english: "ли", chinese: "吗", pinyin: "ma" },
];

export const lesson2Vocabulary = [
  { english: "дърво", chinese: "木", pinyin: "mù" },
  { english: "корен", chinese: "本", pinyin: "běn" },
  { english: "също", chinese: "也", pinyin: "yě" },
  { english: "врата", chinese: "门", pinyin: "mén" },
  { english: "прекалено", chinese: "太", pinyin: "tài" },
  { english: "осем", chinese: "八", pinyin: "bā" },
  { english: "той", chinese: "他", pinyin: "tā" },
  { english: "тя", chinese: "她", pinyin: "tā" },
  { english: "суфикс за мн.ч.", chinese: "们", pinyin: "men" },
  { english: "ти", chinese: "你", pinyin: "nǐ" },
  { english: "Вие", chinese: "您", pinyin: "nín" },
  { english: "не", chinese: "不", pinyin: "bù" },
  { english: "пет", chinese: "五", pinyin: "wǔ" },
  { english: "мъж", chinese: "男", pinyin: "nán" },
  { english: "аз", chinese: "我", pinyin: "wǒ" },
];

export const lesson3Vocabulary = [
  { english: "шест", chinese: "六", pinyin: "liù" },
  { english: "седем", chinese: "七", pinyin: "qī" },
  { english: "десет", chinese: "十", pinyin: "shí" },
  { english: "девет", chinese: "九", pinyin: "jiǔ" },
  { english: "малка сестра", chinese: "妹妹", pinyin: "mèimei" },
  { english: "голяма сестра", chinese: "姐姐", pinyin: "jiějie" },
  { english: "четири", chinese: "四", pinyin: "sì" },
  { english: "и", chinese: "和", pinyin: "hé" },
  { english: "имам", chinese: "有", pinyin: "yǒu" },
  { english: "зает", chinese: "忙", pinyin: "máng" },
  { english: "много", chinese: "很", pinyin: "hěn" },
  { english: "съм", chinese: "是", pinyin: "shì" },
  { english: "китайски език", chinese: "汉语", pinyin: "hànyǔ" },
  { english: "уча", chinese: "学", pinyin: "xué" },
  { english: "труден", chinese: "难", pinyin: "nán" },
  { english: "малък брат", chinese: "弟弟", pinyin: "dìdi" },
  { english: "голям брат", chinese: "哥哥", pinyin: "gēge" },
  { english: "баща", chinese: "爸爸", pinyin: "bàba" },
];

export const lesson4Vocabulary = [
  { english: "руски език", chinese: "俄语", pinyin: "éyǔ" },
  { english: "отивам", chinese: "去", pinyin: "qù" },
  { english: "френски език", chinese: "法语", pinyin: "fǎyǔ" },
  { english: "утре", chinese: "明天", pinyin: "míngtiān" },
  { english: "виждам", chinese: "见", pinyin: "jiàn" },
  { english: "английски език", chinese: "英语", pinyin: "yīngyǔ" },
  { english: "да, правилен", chinese: "对", pinyin: "duì" },
  { english: "български език", chinese: "保加利亚语", pinyin: "bǎojiālìyàyǔ" },
  { english: "арабски език", chinese: "阿拉伯语", pinyin: "ālābóyǔ" },
  { english: "испански език", chinese: "西班牙语", pinyin: "xībānyáyǔ" },
  { english: "немски език", chinese: "德语", pinyin: "déyǔ" },
  { english: "корейски език", chinese: "韩国语", pinyin: "hánguóyǔ" },
  { english: "японски език", chinese: "日语", pinyin: "rìyǔ" },
  { english: "италиански език", chinese: "意大利语", pinyin: "yìdàlìyǔ" },
  { english: "поща", chinese: "邮局", pinyin: "yóujú" },
  { english: "изпращам (писмо)", chinese: "寄", pinyin: "jì" },
  { english: "писмо", chinese: "信", pinyin: "xìn" },
  { english: "банка", chinese: "银行", pinyin: "yínháng" },
  { english: "тегля (пари)", chinese: "取", pinyin: "qǔ" },
  { english: "пари", chinese: "钱", pinyin: "qián" },
];

export const lesson5Vocabulary = [
  { english: "днес", chinese: "今天", pinyin: "jīntiān" },
  { english: "вчера", chinese: "昨天", pinyin: "zuótiān" },
  { english: "седмица", chinese: "星期", pinyin: "xīngqī" },
  { english: "колко, няколко", chinese: "几", pinyin: "jǐ" },
  { english: "този", chinese: "这", pinyin: "zhè" },
  { english: "онзи", chinese: "那", pinyin: "nà" },
  { english: "тук", chinese: "这儿", pinyin: "zhèr" },
  { english: "там", chinese: "那儿", pinyin: "nàr" },
  { english: "къде", chinese: "哪儿", pinyin: "nǎr" },
  { english: "връщам се", chinese: "回", pinyin: "huí" },
  { english: "училище", chinese: "学校", pinyin: "xuéxiào" },
  { english: "ученик", chinese: "学生", pinyin: "xuéshēng" },
  { english: "довиждане", chinese: "再见", pinyin: "zàijiàn" },
  { english: "извинете", chinese: "对不起", pinyin: "duìbuqǐ" },
  { english: "няма проблем", chinese: "没关系", pinyin: "méi guānxi" },
  { english: "Тиенанмън", chinese: "天安门", pinyin: "tiān'ānmén" },
  { english: "Пекин", chinese: "北京", pinyin: "Běijīng" },
];

export const lesson6Vocabulary = [
  { english: "работа", chinese: "工作", pinyin: "gōngzuò" },
  { english: "здраве, тяло", chinese: "身体", pinyin: "shēntǐ" },
  { english: "учител", chinese: "老师", pinyin: "lǎoshī" },
  { english: "моля", chinese: "请", pinyin: "qǐng" },
  { english: "влизам", chinese: "进", pinyin: "jìn" },
  { english: "сядам", chinese: "坐", pinyin: "zuò" },
  { english: "пия", chinese: "喝", pinyin: "hē" },
  { english: "чай", chinese: "茶", pinyin: "chá" },
  { english: "благoдаря", chinese: "谢谢", pinyin: "xièxiè" },
  { english: "не защо", chinese: "不客气", pinyin: "bú kèqi" },
];

export const lesson7Vocabulary = [
  { english: "Китай", chinese: "中国", pinyin: "zhōngguó" },
  { english: "казвам се, викам", chinese: "叫", pinyin: "jìao" },
  { english: "какво", chinese: "什么", pinyin: "shénme" },
  { english: "име", chinese: "名字", pinyin: "míngzi" },
  { english: "фамилия", chinese: "姓", pinyin: "xìng" },
  { english: "уважаемо фамилно име", chinese: "贵姓", pinyin: "guìxìng" },
  { english: "може ли да попитам", chinese: "请问", pinyin: "qǐngwèn" },
  { english: "изучавам", chinese: "学习", pinyin: "xuéxí" },
  { english: "познавам, запознавам се", chinese: "认识", pinyin: "rènshi" },
  { english: "кой", chinese: "谁", pinyin: "shéi" },
  { english: "радостен", chinese: "高兴", pinyin: "gāoxìng" },
  { english: "висок", chinese: "高", pinyin: "gāo" },
  { english: "скъп", chinese: "贵", pinyin: "guì" },
  { english: "Китайски език (писмен)", chinese: "中文", pinyin: "zhōngwén" },
  { english: "книга", chinese: "书", pinyin: "shū" },
  { english: "на", chinese: "的", pinyin: "de" },
];

export const lesson8Vocabulary = [
  { english: "произношение", chinese: "发音", pinyin: "fāyīn" },
  { english: "списание", chinese: "杂志", pinyin: "zázhì" },
  { english: "САЩ", chinese: "美国", pinyin: "měiguó" },
  { english: "две, два", chinese: "两", pinyin: "liǎng" },
  { english: "някои, няколко", chinese: "些", pinyin: "xiē" },
  { english: "Джанг Донг", chinese: "张东", pinyin: "zhāng dōng" },
  { english: "броен класификатор", chinese: "个", pinyin: "gè" },
];

export const lesson9Vocabulary = [
  { english: "обед", chinese: "中午", pinyin: "zhōngwǔ" },
  { english: "ям", chinese: "吃", pinyin: "chī" },
  { english: "мантоу", chinese: "馒头", pinyin: "mántou" },
  { english: "ориз (сготвен)", chinese: "米饭", pinyin: "mǐfàn" },
  { english: "искам, трябва", chinese: "要", pinyin: "yào" },
  { english: "алкохол", chinese: "酒", pinyin: "jiǔ" },
  { english: "пелмени", chinese: "饺子", pinyin: "jiǎozi" },
  { english: "столова", chinese: "食堂", pinyin: "shítáng" },
  { english: "яйце", chinese: "鸡蛋", pinyin: "jīdàn" },
  { english: "супа", chinese: "汤", pinyin: "tāng" },
  { english: "бира", chinese: "啤酒", pinyin: "píjiǔ" },
  { english: "баодзъ", chinese: "包子", pinyin: "bāozi" },
  { english: "нудли", chinese: "面条", pinyin: "miàntiáo" },
  { english: "Мери", chinese: "玛丽", pinyin: "mǎlì" },
];

export const lesson10Vocabulary = [
  { english: "купувам", chinese: "买", pinyin: "mǎi" },
  { english: "продавам", chinese: "卖", pinyin: "mài" },
  { english: "колко", chinese: "多少", pinyin: "duōshao" },
  { english: "много", chinese: "多", pinyin: "duō" },
  { english: "малко", chinese: "少", pinyin: "shǎo" },
  { english: "юан (разговорно)", chinese: "块", pinyin: "kuài" },
  { english: "юан", chinese: "元", pinyin: "yuán" },
  { english: "1/10 юан (разговорно)", chinese: "毛", pinyin: "máo" },
  { english: "1/10 юан", chinese: "角", pinyin: "jiǎo" },
  { english: "1/100 юан", chinese: "分", pinyin: "fēn" },
  { english: "половин килограм", chinese: "斤", pinyin: "jīn" },
  { english: "килограм", chinese: "公斤", pinyin: "gōngjīn" },
  { english: "плодове", chinese: "水果", pinyin: "shuǐguǒ" },
  { english: "ябълка", chinese: "苹果", pinyin: "píngguǒ" },
  { english: "евтин", chinese: "便宜", pinyin: "piányi" },
  { english: "връщам се, давам", chinese: "来", pinyin: "lái" },
  { english: "малко", chinese: "一点儿", pinyin: "yì diǎnr" },
  { english: "друг", chinese: "别的", pinyin: "bié de" },
  { english: "мандарина", chinese: "橘子", pinyin: "júzi" },
  { english: "общо", chinese: "一共", pinyin: "yígòng" },
  { english: "давам", chinese: "给", pinyin: "gěi" },
  { english: "връщам", chinese: "找", pinyin: "zhǎo" },
  { english: "как, защо", chinese: "怎么", pinyin: "zěnme" },
  { english: "частица за предложение", chinese: "吧", pinyin: "ba" },
  { english: "още", chinese: "还", pinyin: "hái" },
];

export const lesson11Vocabulary = [
  { english: "следобед", chinese: "下午", pinyin: "xiàwǔ" },
  { english: "сутрин", chinese: "上午", pinyin: "shàngwǔ" },
  { english: "библиотека", chinese: "图书馆", pinyin: "túshūguǎn" },
  { english: "обменям, сменям", chinese: "换", pinyin: "huàn" },
  { english: "госпожица", chinese: "小姐", pinyin: "xiǎojiě" },
  { english: "служител, продавач", chinese: "营业员", pinyin: "yíngyèyuán" },
  { english: "ренминби", chinese: "人民币", pinyin: "rénmínbì" },
  { english: "сто", chinese: "一百", pinyin: "yì bǎi" },
  { english: "хиляда", chinese: "一千", pinyin: "yì qiān" },
  { english: "десет хиляди", chinese: "一万", pinyin: "yí wàn" },
  { english: "долар", chinese: "美元", pinyin: "měiyuán" },
  { english: "йен", chinese: "日元", pinyin: "rìyuán" },
  { english: "евро", chinese: "欧元", pinyin: "ōuyuán" },
  { english: "вон", chinese: "韩元", pinyin: "hányuán" },
  { english: "чакам", chinese: "等", pinyin: "děng" },
  { english: "малко (време)", chinese: "一会儿", pinyin: "yí huìr" },
  { english: "господин", chinese: "先生", pinyin: "xiānsheng" },
  { english: "броя", chinese: "数", pinyin: "shǔ" },
];

export const hanyuJiaochengLesson1Vocabulary = [
];

export const hsk1Lesson1Vocabulary = [
  { english: "hello", chinese: "你好", pinyin: "nǐ hǎo" },
  { english: "Ms. Wang", chinese: "王老师", pinyin: "Wáng lǎoshī" },
  { english: "everybody", chinese: "大家", pinyin: "dàjiā" },
  { english: "good; fine", chinese: "好", pinyin: "hǎo" },
  { english: "student", chinese: "学生", pinyin: "xuésheng" },
  { english: "suffix for plural", chinese: "们", pinyin: "men" },
  { english: "teacher", chinese: "老师", pinyin: "lǎoshī" },
  { english: "you (polite)", chinese: "您", pinyin: "nín" },
  { english: "you (plural)", chinese: "你们", pinyin: "nǐmen" },
  { english: "thank you", chinese: "谢谢", pinyin: "xièxiè" },
  { english: "you're welcome", chinese: "不客气", pinyin: "bú kèqi" },
  { english: "classmate", chinese: "同学", pinyin: "tóngxué" },
  { english: "goodbye", chinese: "再见", pinyin: "zàijiàn" }
];